res = 5
try:
    print(Res)
except NameError:
    print("Escaping NameError")